---
spring:
  profiles: cloud
  cloud:
    services:
      registrationMethod: route
  data:
    mongodb:
      database: carts
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    registerWithEureka: true
    serviceUrl: ${vcap.services.discovery.credentials.uri}/eureka/