---
spring:
  profiles: cloud
  cloud:
    services:
      registrationMethod: route
webapp:
  background:
    color: blue
management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  routes:
    inventory-service:
      path: /inventory/**
      serviceId: inventory-service
      sensitiveHeaders:
      stripPrefix: true
    cart-service:
      path: /cart/**
      serviceId: cart-service
      sensitiveHeaders:
      stripPrefix: true
    product-service:
      path: /product/**
      serviceId: product-service
      sensitiveHeaders:
      stripPrefix: true
  ignored-services: '*'
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${vcap.services.discovery.credentials.uri}/eureka/
    fetch-registry: true
security:
  oauth2:
    client:
      client-id: ${vcap.services.uaa.credentials.client_id}
      client-secret: ${vcap.services.uaa.credentials.client_secret}
      access-token-uri: ${vcap.services.uaa.credentials.url}/oauth/token
      user-authorization-uri: ${vcap.services.uaa.credentials.url}/oauth/authorize
      scope: openid
    resource:
      user-info-uri: ${vcap.services.uaa.credentials.url}/userinfo
      token-info-uri: ${vcap.services.uaa.credentials.url}/introspect
      prefer-token-info: false
hystrix:
  shareSecurityContext: true