---
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: cloud
databaseUrl: ${cloud.services.mysql.connection.jdbcurl:jdbc:h2:mem:test}
products:
  a: ${PRODUCTS_A:#{null}}
  b: ${PRODUCTS_B:#{null}}
  c: ${PRODUCTS_C:#{null}}
app:
  version: "updated!"
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    registerWithEureka: true
    serviceUrl: ${vcap.services.discovery.credentials.uri}/eureka/
---
spring:
  profiles: mysql
  datasource:
    url: ${cloud.services.mysql.connection.jdbcurl}
    username: ${cloud.services.mysql.connection.username}
    password: ${cloud.services.mysql.connection.password}
    tomcat:
      test-on-borrow: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
